version: 2
jobs:

  gitflow:
    docker:
      - image: circleci/node:8.5
    steps:
      - run:
          name: Check valid branch name
          command: |
            invalid=1
            if [[ $CIRCLE_BRANCH == 'master' ]]; then invalid=0; fi
            if [[ $CIRCLE_BRANCH == 'f/'* ]]; then invalid=0; fi
            if [[ $invalid == 1 ]]; then exit 1; fi

  api:
    docker:
      - image: circleci/node:8.5
      - image: circleci/mongo:3.5.6
    working_directory: ~/arqui/api
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - api-v1-{{ checksum "package.json" }}
          - api-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: api-v1-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test:ci
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/junit.xml
          destination: junit/junit.xml
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage

  email:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/email
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - email-v1-{{ checksum "package.json" }}
          - email-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: email-v1-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test:ci
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/junit.xml
          destination: junit/junit.xml
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage

  queue:
    docker:
      - image: circleci/node:8.5
      - image: redis:4-alpine
    working_directory: ~/arqui/queue
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - queue-v1-{{ checksum "package.json" }}
          - queue-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: queue-v1-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test:ci
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/junit.xml
          destination: junit/junit.xml
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage

  queue-visualizer:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/queue-visualizer
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - queue-visualizer-v1-{{ checksum "package.json" }}
          - queue-visualizer-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: queue-visualizer-v1-{{ checksum "package.json" }}
      - run: yarn lint

  web:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/web
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - web-v1-{{ checksum "package.json" }}
          - web-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: web-v1-{{ checksum "package.json" }}
      # - run: yarn lint

  docker-api:
    docker:
      - image: circleci/node:8.5
        environment:
          REPO: negebauer/iic2173-arqui-api
          TAG_CI: circleci
    working_directory: ~/arqui/api
    steps:
      - checkout:
          path: ~/arqui
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t $REPO .
      - run: docker tag $REPO $REPO:$(git describe)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $REPO:$(git describe)
      - run: docker push $REPO

  docker-email:
    docker:
      - image: circleci/node:8.5
        environment:
          REPO: negebauer/iic2173-arqui-email
          TAG_CI: circleci
    working_directory: ~/arqui/email
    steps:
      - checkout:
          path: ~/arqui
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t $REPO .
      - run: docker tag $REPO $REPO:$(git describe)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $REPO:$(git describe)
      - run: docker push $REPO

  docker-queue:
    docker:
      - image: circleci/node:8.5
        environment:
          REPO: negebauer/iic2173-arqui-queue
          TAG_CI: circleci
    working_directory: ~/arqui/queue
    steps:
      - checkout:
          path: ~/arqui
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t $REPO .
      - run: docker tag $REPO $REPO:$(git describe)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $REPO:$(git describe)
      - run: docker push $REPO

  docker-queue-visualizer:
    docker:
      - image: circleci/node:8.5
        environment:
          REPO: negebauer/iic2173-arqui-queue-visualizer
          TAG_CI: circleci
    working_directory: ~/arqui/queue-visualizer
    steps:
      - checkout:
          path: ~/arqui
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t $REPO .
      - run: docker tag $REPO $REPO:$(git describe)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $REPO:$(git describe)
      - run: docker push $REPO

  docker-web:
    docker:
      - image: circleci/node:8.5
        environment:
          REPO: negebauer/iic2173-arqui-web
          TAG_CI: circleci
    working_directory: ~/arqui/web
    steps:
      - checkout:
          path: ~/arqui
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: docker build -t $REPO .
      - run: docker tag $REPO $REPO:$(git describe)
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $REPO:$(git describe)
      - run: docker push $REPO

  deploy:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/docker
    steps:
      - checkout:
          path: ~/arqui
      - add_ssh_keys:
          fingerprints:
            - "f7:76:78:2a:7c:64:4c:5c:86:39:c1:be:4d:a5:00:78"
            - "8d:64:9e:30:9b:c2:e2:f1:a1:7f:5b:57:e5:d7:a7:66"
      - run:
          name: Make docker images version explicit
          command: |
            file=docker-compose-stack.yml
            version=$(git describe)
            image_regex=negebauer/iic2173-arqui-
            images=$(cat $file | grep $image_regex)
            for image in $images; do
              [[ $image == "$image_regex"* ]] || continue
              version_regex=(.+):latest
              [[ $image =~ $version_regex ]] && image_versioned="${BASH_REMATCH[1]}:${version}"
              sed -i.backup "s~$image~$image_versioned~g" $file
            done
      - run:
          name: Copy stack config
          command: |
            scp -o "StrictHostKeyChecking no" docker-compose-stack.yml administrator@arqss2.ing.puc.cl:.
            scp -o "StrictHostKeyChecking no" docker-compose-stack.yml administrator@arqss7.ing.puc.cl:.
      - run:
          name: Deploy arqui stack
          command: |
            ssh administrator@arqss2.ing.puc.cl 'docker stack deploy -c docker-compose-stack.yml arqui' ||
            ssh administrator@arqss7.ing.puc.cl 'docker stack deploy -c docker-compose-stack.yml arqui'

  docker_maintenance:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/docker
    steps:
      - checkout:
          path: ~/arqui
      - add_ssh_keys:
          fingerprints:
            - "f7:76:78:2a:7c:64:4c:5c:86:39:c1:be:4d:a5:00:78"
            - "8d:64:9e:30:9b:c2:e2:f1:a1:7f:5b:57:e5:d7:a7:66"
            - "19:c3:b8:00:3c:90:04:b4:b8:3e:d7:99:8b:9c:44:03"
            - "8b:7f:8a:2c:6d:0a:7a:40:0e:ad:ea:99:1c:31:13:8b"
            - "15:56:6d:15:da:2a:a9:f3:3a:fb:99:52:40:c0:3a:63"
      - run:
          name: Docker system prune
          command: |
            for machine in 2 7 11 12 13; do
              ssh -o "StrictHostKeyChecking no" administrator@arqss${machine}.ing.puc.cl '
                echo y | docker system prune
              '
            done

workflows:
  version: 2
  workflow:
      jobs:
        - gitflow
        - api
        - email
        - queue
        - queue-visualizer
        - web
        - docker-api:
            requires:
              - api
            filters:
              branches:
                only:
                  - master
        - docker-email:
            requires:
              - email
            filters:
              branches:
                only:
                  - master
        - docker-queue:
            requires:
                - queue
            filters:
              branches:
                only:
                  - master
        - docker-queue-visualizer:
            requires:
                - queue-visualizer
            filters:
              branches:
                only:
                  - master
        - docker-web:
            requires:
              - web
            filters:
              branches:
                only:
                  - master
        - deploy:
            requires:
              - gitflow
              - docker-api
              - docker-email
              - docker-queue
              - docker-queue-visualizer
              - docker-web
            filters:
              branches:
                only:
                  - master
        - docker_maintenance:
            requires:
              - deploy
            filters:
              branches:
                only:
                  - master
