defaults: &defaults
  working_directory: ~/arqui
  docker:
    - image: negebauer/iic2173-arqui-build:0.0.1

version: 2
jobs:
  clone:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  api:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./api
      - run: cd api
      - run: ls

  email:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./email
      - run: cd email
      - run: ls

  queue:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./queue
      - run: cd queue
      - run: ls

  web:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./web
      - run: cd web
      - run: ls

  docker:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: ls

workflows:
  version: 2
  workflow:
      jobs:
        - clone
        - api:
            requires:
              - clone
        - email:
            requires:
              - clone
        - queue:
            requires:
              - clone
        - web:
            requires:
              - clone
        - docker:
            requires:
              - api
              - email
              - queue
              - web
        - deploy:
            requires:
              - docker
            filters:
              branches:
                only:
                  - master
