version: 2
jobs:
  api:
    docker:
      - image: circleci/node:8.5
      - image: circleci/mongo:3.5.6
    working_directory: ~/arqui/api
    steps:
      - checkout:
          path: ~/arqui
      - restore_cache:
          keys:
          - api-v1-{{ checksum "package.json" }}
          - api-v1-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: api-v1-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test:ci

  email:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/email
    steps:
      - checkout:
          path: ~/arqui
      - run: pwd; ls

  queue:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/queue
    steps:
      - checkout:
          path: ~/arqui
      - run: pwd; ls

  web:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/arqui/web
    steps:
      - checkout:
          path: ~/arqui
      - run: pwd; ls

  docker:
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - run: pwd ; ls
      - run: ls docker

  deploy:
    docker:
      - image: circleci/node:8.5
    steps:
      - run: echo "NOT IMPLEMENTED"

workflows:
  version: 2
  workflow:
      jobs:
        - api
        - email
        - queue
        - web
        - docker:
            requires:
              - api
              - email
              - queue
              - web
        - deploy:
            requires:
              - docker
            filters:
              branches:
                only:
                  - master
