version: "3"
services:

  api:
    image: negebauer/iic2173-arqui-api
    # build: ../api
    environment:
      - MONGO=mongodb://mongo/IIC2173-Arqui-test
    ports:
      - "3000:80"
    networks:
      - proxy

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data/mongodb/db:/data/db"
    networks:
      - proxy

  web:
    image: negebauer/iic2173-arqui-web
    # build: ../web
    environment:
      - API=http://localhost:3000
    ports:
      - "8080:80"
    networks:
      - proxy

  queue:
    image: negebauer/iic2173-arqui-queue
    # build: ../queue
    environment:
      - API_URL=http://localhost:3000
      - REDIS_HOST=redis
    ports:
      - "3002:80"
    networks:
      - proxy

  queue-visualizer:
    image: negebauer/iic2173-arqui-queue-visualizer
    # build: ../queue-visualizer
    environment:
      - REDIS_HOST=redis
    ports:
      - "3003:80"
    networks:
      - proxy

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - "~/data/redis/db:/data"
    networks:
      - proxy

networks:
  proxy:
