version: "3"
services:
  api:
    image: negebauer/iic2173-arqui-api:dev
    environment:
      - MONGO=mongodb://api-mongo/IIC2173-Arqui-test
    ports:
      - "3000:80"
    networks:
      - arqui-network
      - api-network

  api-mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data/mongodb/db:/data/db"
    networks:
      - api-network

  web:
    image: negebauer/iic2173-arqui-web:dev
    environment:
      - API=http://localhost:3000
    ports:
      - "8080:80"
    networks:
      - arqui-network

networks:
  arqui-network:
  api-network:
