version: "3"
services:
  api:
    image: negebauer/iic2173-arqui-api:dev
    environment:
      - MONGO=mongodb://api-mongo/IIC2173-Arqui
      - PORT=80
    ports:
      - "3000:80"
    links:
      - api-mongo
  api-mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
