version: "3"
services:

  api:
    # image: negebauer/iic2173-arqui-api
    build: ../api
    environment:
      - MONGO=mongodb://mongo/IIC2173-Arqui-test
      - MAILER_URI=http://email
      - QUEUE_URI=http://queue
      - API_URI=http://arqss2.ing.puc.cl/api
    ports:
      - "3000:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/data/mongodb/db:/data/db"

  email:
    # image: negebauer/iic2173-arqui-email
    build: ../email
    environment:
      - API_URI=http://api
    ports:
      - "3001:80"

  queue:
    # image: negebauer/iic2173-arqui-queue
    build: ../queue
    environment:
      - API_URI=http://api
      - REDIS_HOST=redis
      - ARQUITRAN_URI=http://arqss16.ing.puc.cl
      - ARQUITRAN_TOKEN=d51f6a66-e670-41c4-8187-2149bc46654e
      - ARQUITRAN_ID=G1
    ports:
      - "3002:80"

  queue-visualizer:
    # image: negebauer/iic2173-arqui-queue-visualizer
    build: ../queue-visualizer
    environment:
      - REDIS_HOST=redis
    ports:
      - "3003:80"

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - "~/data/redis/db:/data"

  telegram:
    # image: negebauer/iic2173-arqui-telegram
    build: ../telegram
    environment:
      - API_URI=http://api
      - TOKEN=485892696:AAHOHg3Sk2CNUt_ArGuv09qxGv9eqJuiY78

  web:
    # image: negebauer/iic2173-arqui-web
    build: ../web
    environment:
      - API=http://localhost:3000
    ports:
      - "8080:80"
