version: "3"
services:

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy

  proxy:
    image: vfarcic/docker-flow-proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - STATS_USER=u
      - STATS_PASS=p
      - MODE=swarm
    deploy:
      mode: global
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy

  mongo:
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles"]
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 1m30s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=27017
    ports:
      - "27017:27017"
    volumes:
      - "/home/administrator/data/mongodb/db:/data/db"
    networks:
      - proxy

  mongo-ctrl:
    image: martel/mongo-replica-ctrl:latest
    entrypoint: python /src/replica_ctrl.py
    environment:
      - OVERLAY_NETWORK_NAME=proxy
      - MONGO_SERVICE_NAME=arqui_mongo
      - REPLICASET_NAME=rs
      - MONGO_PORT=27017
      # - DEBUG=1 #uncomment to debug the script
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    depends_on:
      - mongo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy

  redis-master:
    image: redis:3
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/administrator/data/redis/db:/data"
    networks:
      - proxy

  redis-slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/administrator/data/redis/db:/data"
    networks:
      - proxy

  redis-sentinel:
    image: aoskog/redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy

  api:
    image: negebauer/iic2173-arqui-api:dev
    environment:
      - MONGO=mongodb://mongo/IIC2173-Arqui?replicaSet=rs
      - API_QUEUE_SECRET=secretapiqueue
    deploy:
      replicas: 14
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/api
        - com.df.port=80
        - com.df.reqPathSearch=/api
        - com.df.reqPathReplace=
      restart_policy:
        condition: on-failure
      # placement:
        # constraints: [node.role != manager]
    depends_on:
      - mongo
    networks:
      - proxy

  web:
    image: negebauer/iic2173-arqui-web:dev
    environment:
      - API=http://arqss2.ing.puc.cl/api
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=80
      # placement:
        # constraints: [node.role != manager]
    networks:
      - proxy

  visualizer:
    image: dockersamples/visualizer:stable
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/v
        - com.df.port=8080
        - com.df.reqPathSearch=/v
        - com.df.reqPathReplace=
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy

  queue:
    image: negebauer/iic2173-arqui-queue:dev
    environment:
      - API_URL=http://api
      - API_QUEUE_SECRET=secretapiqueue
      - REDIS_PORT=6379
      - REDIS_HOST=redis-master
      - REDIS_PASS=
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/queue
        - com.df.port=80
        - com.df.reqPathSearch=/queue
        - com.df.reqPathReplace=
      placement:
        constraints: [node.role != manager]
    depends_on:
      - redis-master
      - redis-slave
      - redis-sentinel
    networks:
      - proxy

  queue-visualizer:
    image: negebauer/iic2173-arqui-queue-visualizer:dev
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis-master
      - REDIS_PASS=
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/qv
        - com.df.port=80
        - com.df.reqPathSearch=/qv
        - com.df.reqPathReplace=
      placement:
        constraints: [node.role == manager]
    depends_on:
      - redis-master
      - redis-slave
      - redis-sentinel
    networks:
      - proxy

networks:
  proxy:
    external: true
    # driver: overlay
