version: '3'
services:

  api:
    image: negebauer/iic2173-arqui-api:dev
    deploy:
      replicas: 10
    environment:
      - MONGO=mongodb://mongo/IIC2173-Arqui-test
    depends_on:
      - mongo
    ports:
      - "8080:80"
    networks:
      - network

  mongo:
    image: mongo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "27017:27017"
    volumes:
      - "/home/administrator/data/mongodb/db:/data/db"
    networks:
      - network

  visualizer:
    image: dockersamples/visualizer:stable
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network

networks:
  network:
